name: guardsys

description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #  Firebase knihovny
  firebase_storage: ^11.5.6
  firebase_messaging: ^14.7.10
  cloud_firestore: ^4.15.5
  firebase_app_check: ^0.2.1+8
  firebase_core: ^2.25.4
  firebase_auth: ^4.15.3

  #  Ostatní knihovny
  shared_preferences: ^2.2.2
  file_selector: ^1.0.3
  pdfx: ^2.5.0
  path_provider: ^2.1.1
  dio: ^5.4.0
  logger: ^2.0.2+1
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  image_picker: ^1.0.5
  encrypt: ^5.0.3
  crypto: ^3.0.3
  flutter_dotenv: ^5.1.0
  url_launcher: ^6.2.5
  device_info_plus: ^9.1.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/zelene.jpg
    - assets/images/panorama.jpg
    - assets/images/lazne.jpg

dependency_overrides:
  flutter_local_notifications_linux: null 