name: guardsys

description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # 📦 Firebase knihovny
  firebase_storage: ^11.6.0
  firebase_messaging: ^14.7.10
  cloud_firestore: ^4.13.6
  firebase_app_check: ^0.2.1+14
  firebase_core: ^2.26.0
  firebase_auth: ^4.17.7

  # 📂 Ostatní knihovny
  file_selector: ^1.0.3
  pdfx: ^2.6.0
  path_provider: ^2.1.1
  dio: ^5.3.3
  logger: ^2.0.2+1
  cupertino_icons: ^1.0.6
  intl: ^0.18.1
  image_picker: ^1.0.5
  encrypt: ^5.0.3
  crypto: ^3.0.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/zelene.jpg
    - assets/images/panorama.jpg
    - assets/images/lazne.jpg

dependency_overrides:
  flutter_local_notifications_linux: null 